name: CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install the project dependencies
        run: npm install

      - name: Fix code style issues with prettier & eslint
        run: npm run lint:fix && npm run prettier:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling

  test:
    runs-on: ubuntu-latest
    env:
      APP_API_URL: ${{ secrets.APP_API_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: .env setting
        run: |
          echo "APP_API_URL=${{ secrets.APP_API_URL }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project dependencies
        run: npm install

      - name: Run tests
        run: npm run jest

  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 21.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project dependencies
        run: npm install

      - name: Build the project
        run: npm run build